In [1]:
import numpy as np

In [11]:
array1 = np.array([1, 2, 3])
print('array1 type: ', type(array1))
print('array1 array 형태: ', array1.shape)

array2 = np.array([[1,2,3],[2,3,4]])
print('array2 type: ', type(array2))
print('array2 array 형태: ', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type: ', type(array3))
print('array3 array 형태: ', array3.shape)

array4 = np.array([[[1,2,3], [4,5,6]]])
print('array4 type: ', type(array4))
print('array4 array 형태: ', array4.shape)

array1 type:  <class 'numpy.ndarray'>
array1 array 형태:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2 array 형태:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3 array 형태:  (1, 3)
array4 type:  <class 'numpy.ndarray'>
array4 array 형태:  (1, 2, 3)


In [12]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원, array4: {:3}차원'.format(array1.ndim, array2.ndim, array3.ndim, array4.ndim))

print('array1: {0}차원, array2: {1}차원, array3: {2}차원, array4: {3}차원'.format(array1.ndim, array2.ndim, array3.ndim, array4.ndim))

array1: 1차원, array2: 2차원, array3:  2차원, array4:   3차원
array1: 1차원, array2: 2차원, array3: 2차원, array4: 3차원


In [13]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [14]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [16]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int = array_float.astype('int32')
print(array_int, array_int.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [3]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [7]:
print(np.arange(10, 20))
print(np.arange(19, 40, 2))
print(np.arange(30.2, 30, -0.1))

[10 11 12 13 14 15 16 17 18 19]
[19 21 23 25 27 29 31 33 35 37 39]
[30.2 30.1]


In [9]:
zero_array = np.zeros((2, 3), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0 0]
 [0 0 0]]
int32 (2, 3)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [10]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(2, 5)
print("array2:\n", array2)

[0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [15]:
array3 = np.arange(12)
print(array3, "\n")

array4 = array3.reshape(2, 2, 3)
print("array4:\n", array4)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

array4:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [16]:
array5 = array1.reshape(4, 3)
print(array5)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [17]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print('array2 shape: ', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape: ', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape:  (2, 5)
array3 shape:  (5, 2)


In [20]:
# create 1-dimension ndarray from 1 to 9
array1 = np.arange(start=1, stop=10)
print('array1: ', array1)

# index starts from 0, so array1[2] is at third index of list 
value = array1[2]
print('value: ', value)
print(type(value))

# minus indexing
print("맨 뒤의 값 : ", array1[-1], "맨 위에서 두 번째 값 : ", array1[-2])

# change value by single-indexing 
array1[0] =  9
array1[8] = 0
print("array1: ", array1)

array1:  [1 2 3 4 5 6 7 8 9]
value:  3
<class 'numpy.int64'>
맨 뒤의 값 :  9 맨 위에서 두 번째 값 :  8
array1:  [9 2 3 4 5 6 7 8 0]


In [21]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값: ', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값: ', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값: ', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값: ', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값:  1
(row=0, col=1) index 가리키는 값:  2
(row=1, col=0) index 가리키는 값:  4
(row=2, col=2) index 가리키는 값:  9


In [4]:
array1 = np.array([[1,2,3], [4,5,6]])
array2 = np.array([[7,8], [9,10], [11,12]])
dot_product = np.dot(array1, array2)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [6]:
A = np.array([[1,2],[3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬: \n', transpose_mat)

A의 전치 행렬: 
 [[1 3]
 [2 4]]


In [9]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

# sort ndarray by np.sort()
sorted_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬: ', sorted_array1)
print('np.sort() 호출 후 원본 행렬: ', org_array)

# sort ndarray by ndarray.sort()
sorted_array2 = org_array.sort()
print('ndarray.sort() 호출 후 반환된 행렬: ', sorted_array2)
print('ndarray.sort() 호출 후 원본 행렬: ', org_array)

array2d = np.array([[8,12],[7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('row 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('column 방향으로 정렬:\n', sort_array2d_axis1)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬:  [1 3 5 9]
np.sort() 호출 후 원본 행렬:  [3 1 9 5]
ndarray.sort() 호출 후 반환된 행렬:  None
ndarray.sort() 호출 후 원본 행렬:  [1 3 5 9]
row 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
column 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [10]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스: ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스:  [1 0 3 2]


In [11]:
sort_indices_desc = np.argsort(org_array)[::-1]
print(type(sort_indices_desc))
print("행렬 내림차순 정렬 시 원본 행렬의 인덱스: ", sort_indices_desc)

<class 'numpy.ndarray'>
행렬 내림차순 정렬 시 원본 행렬의 인덱스:  [2 3 0 1]


In [12]:
print(org_array)

[3 1 9 5]


In [14]:
name_array = np.array(['John', 'Wike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])
sort_indices_asc = np.argsort(score_array) # argsort()
print('성적 오름차순 정렬 시 score_array의 인덱스: ', sort_indices_asc) 
print('성적 오름차순으로 name_array의 이름 출력: ', name_array[sort_indices_asc]) # fancy indexing

성적 오름차순 정렬 시 score_array의 인덱스:  [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력:  ['John' 'Sarah' 'Samuel' 'Wike' 'Kate']


In [16]:
array1d = np.arange(1, 10)

# applying "array1d > 5" Boolean Indexing in [ ]
array3 = array1d[array1d > 5]
print('array1d > 5 Boolean Indexing result : ', array3)
print(array1d)

array1d > 5 Boolean Indexing result :  [6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [17]:
print(array1d > 5)

[False False False False False  True  True  True  True]


In [18]:
print(type(array3))

<class 'numpy.ndarray'>


In [21]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)

print(array2d)

array3 = array2d[[0,1], 2]
print('array2d[[0, 1], 2] => ', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0, 1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


In [22]:
array1 = np.arange(1, 10)
array3 = array1[0:3]
print(array3)
print(type(array3))
print(array1)

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


In [24]:
array4 = array1[:3]
print(array4)

[1 2 3]


In [26]:
array5 = array1[3:]
print(array5)

[4 5 6 7 8 9]


In [27]:
array6 = array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]


In [30]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3], "\n")

print(array2d[0])
print(array2d[1])
print('array2d[0] shape : ', array2d[0].shape, 'array2d[1] shape', array2d[1].shape)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]] 

[1 2 3]
[4 5 6]
array2d[0] shape :  (3,) array2d[1] shape (3,)
